version: '3'

env:
  PATH: 
    sh: echo "$(pwd)/node_modules/.bin:$PATH"

tasks:
  install:
    sources:
      - package.json
    generates:
      - node_modules/**
    cmds:
      - pnpm install

  dev:
    deps: [install]
    cmds:
      - pnpm vite

  build:
    deps: [install]
    cmds:
      - pnpm tsc
      - pnpm vite build
