version: '3'

tasks:
  install:
    sources:
      - pyproject.toml
    generates:
      - .venv/**
    cmds:
      - uv sync

  install-dev:
    sources:
      - pyproject.toml
    generates:
      - .venv/**
    cmds:
      - uv sync --group dev

  test:
    deps: [install-dev]
    cmds:
      - uv run pytest

  dev:
    deps: [install-dev]
    cmds:
      - >
        uv run watchmedo auto-restart
        --patterns="**/*.py"
        --debounce-interval=1
        --ignore-directories
        --recursive
        -- uv run python entry.py

  generate-migration:
    deps: [install-dev]
    cmds:
      - uv run alembic upgrade head
      - uv run alembic revision --autogenerate

  build:
    deps: [install-dev]
    cmds:
      - uv run pyinstaller --noconfirm --name server entry.py
      - uv run python scripts/rename_python_sidecar.py --name=server --output-dir=../src-tauri/
