# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  server:
    taskfile: src-server/taskfile.yaml
    dir: src-server
  frontend:
    taskfile: src-frontend/taskfile.yaml
    dir: src-frontend

tasks:
  default:
    silent: true
    cmds:
      - task --list-all

  install-dev:
    cmds:
      - pnpm install
      - task: frontend:install
      - task: server:install-dev

  dev:
    cmds:
      - tauri dev -- -- --dev

  # this command will automatically called by tauri's beforeDevCommand
  dev-all:
    deps:
      - task: frontend:dev
      - task: server:dev
    parallel: true

  build-all:
    cmds:
      - task: frontend:build
      - task: server:build
