from .daily_assistant import INSTRUCTION as DAILY_ASSISTANT_AGENT_INSTRUCTION
from .software_engineer import INSTRUCTION as SOFTWARE_ENGINEER_AGENT_INSTRUCTION
from .terminal_interpreter import INSTRUCTION as TERMINAL_INTERPRETER_AGENT_INSTRUCTION

__all__ = [
    "DAILY_ASSISTANT_AGENT_INSTRUCTION",
    "SOFTWARE_ENGINEER_AGENT_INSTRUCTION",
    "TERMINAL_INTERPRETER_AGENT_INSTRUCTION",
]
