"""empty message

Revision ID: 1b2f71c9f5a4
Revises: dc3ede484e1e
Create Date: 2026-02-14 16:10:57.948441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from db.models.task import TaskUsage
from db.models.utils import DataClassJSON

# revision identifiers, used by Alembic.
revision: str = '1b2f71c9f5a4'
down_revision: Union[str, Sequence[str], None] = 'dc3ede484e1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage', DataClassJSON(TaskUsage), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('usage')

    # ### end Alembic commands ###
