"""empty message

Revision ID: b0a9467e69b9
Revises: 9a197b6f33e7
Create Date: 2026-01-12 14:07:59.942128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0a9467e69b9'
down_revision: Union[str, Sequence[str], None] = '9a197b6f33e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toolsets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('BUILTIN', 'MCP_LOCAL', 'MCP_REMOTE', name='toolsettype', native_enum=False), nullable=False),
    sa.Column('params', db.models.utils.PydanticJSON(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_approve', sa.Boolean(), nullable=False),
    sa.Column('toolset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['toolset_id'], ['toolsets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tools')
    op.drop_table('toolsets')
    # ### end Alembic commands ###
