"""empty message

Revision ID: f406983b63d0
Revises: f9ec682fe325
Create Date: 2026-04-15 23:21:05.002248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f406983b63d0'
down_revision: Union[str, Sequence[str], None] = 'f9ec682fe325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relative', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('_workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['_workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    # ### end Alembic commands ###
